apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: b0
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "b0",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "b0",
          "isGateway": true,
          "isDefaultGateway": false,
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "10.0.0.0/24",
                  "gateway": "10.0.0.254"
                }
              ]
            ],
            "routes": [
              { "dst": "10.0.0.0/8" },
              { "dst": "172.16.0.0/12" },
              { "dst": "192.168.0.0/16" }
            ]
          }
        },
        {
          "type": "accept-bridge",
          "name": "b0"
        }
      ]
    }'