apiVersion: v1
kind: Service
metadata:
  name: otg-controller
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: grpc
      port: 40051
      protocol: TCP
      targetPort: 40051
    - name: gnmi
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    role: controller
  type: LoadBalancer
