apiVersion: v1
kind: Service
metadata:
  name: otg-port-2
spec:
  ports:
    - name: port-5555
      port: 5555
      protocol: TCP
      targetPort: 5555
    - name: port-50071
      port: 50071
      protocol: TCP
      targetPort: 50071
  selector:
    role: port-2
