apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - controller/controller-cm.yaml
  - controller/controller-svc.yaml
  - controller/controller.yaml

  - engine-1/engine-1-svc.yaml
  - engine-1/engine-1.yaml

  - engine-2/engine-2-svc.yaml
  - engine-2/engine-2.yaml

  - engine-3/engine-3-svc.yaml
  - engine-3/engine-3.yaml
