apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/networks
- ../components/srlinux
- ../components/ixia-c

patches:
- target:
    kind: Pod
    name: srl01
  patch: |-
    - op: replace
      path: /metadata/name
      value: dut
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b1@e1-1,b2@e1-2

- target:
    kind: Pod
    name: srl02
  patch: |-
    $patch: delete
    kind: Pod
    metadata:
      name: srl02

- target:
    kind: Pod
    name: srl03
  patch: |-
    - op: add
      path: /metadata/annotations/config.kubernetes.io~1local-config
      value: "true"

- target:
    kind: Pod
    name: srl04
  patch: |-
    $patch: delete
    kind: Pod
    metadata:
      name: srl04

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b2@eth2

- target:
    kind: Pod
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Pod
    metadata:
      name: otg-port-3

- target:
    kind: Service
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Service
    metadata:
      name: otg-port-3
