apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/srlinux/srl01
- ../components/ixia-c/controller
- ../components/ixia-c/engine-1
- ../components/ixia-c/engine-2
- ../components/networks/b1
- ../components/networks/b2

patches:
- target:
    kind: Pod
    name: srl01
  patch: |-
    - op: replace
      path: /metadata/name
      value: dut
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b1@e1-1,b2@e1-2

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b2@eth2

- target:
    kind: Pod
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Pod
    metadata:
      name: otg-port-3

- target:
    kind: Service
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Service
    metadata:
      name: otg-port-3
