apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: csr01
  labels:
    kubevirt.io/os: iosxe
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: csr01
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        devices:
          autoattachGraphicsDevice: false
          interfaces:
          - name: ge1
            bridge: {}
          - name: ge2
            bridge: {}
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
            name: cdrom0
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: csr01
      - name: cdrom0
        persistentVolumeClaim:
          claimName: csr01day0
      networks:
      - name: ge1
        multus:
          default: true
          networkName: kube-system/cni1
      - name: ge2
        multus:
          networkName: ""