apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: csr01day0
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
  source:
    http:
      url: http://${HTTP_SERVER_IP}:8080/csr_config.iso
