apiVersion: v1
kind: Service
metadata:
  name: csr01
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/domain: csr01
  type: LoadBalancer
