apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/networks
- ../components/ixia-c

patches:
- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n1@eth2
