apiVersion: v1
kind: Pod
metadata:
  name: srl04
  annotations:
    v1.multus-cni.io/default-network: cni1
    k8s.v1.cni.cncf.io/networks: ""
  labels:
    vendor: nokia
spec:
  containers:
  - name: srlinux
    image: ghcr.io/nokia/srlinux:latest
    command:
    - /tini
    - --
    - fixuid
    - -q
    - /entrypoint.sh
    args:
    - sudo
    - bash
    - -c
    - /opt/srlinux/bin/sr_linux
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
    resources:
      limits:
        memory: 4Gi
        cpu: 2000m
      requests:
        memory: 2Gi
        cpu: 800m
    volumeMounts:
      - mountPath: /tmp/topology.yml
        subPath: topology.yml
        name: hw
        readOnly: true
  volumes:
  - name: hw
    configMap:
      name: srl04-hw
      defaultMode: 292
      optional: false
