apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/networks
- ../components/srlinux
- ../components/ixia-c

patches:
- target:
    kind: Pod
    name: srl01
  patch: |-
    - op: replace
      path: /metadata/name
      value: c1
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n1@e1-1,n2@e1-2,n3@e1-3

- target:
    kind: Pod
    name: srl02
  patch: |-
    - op: replace
      path: /metadata/name
      value: c2
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n2@e1-1,n4@e1-2

- target:
    kind: Pod
    name: srl03
  patch: |-
    - op: replace
      path: /metadata/name
      value: c3
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n3@e1-1,n5@e1-2

- target:
    kind: Pod
    name: srl04
  patch: |-
    - op: replace
      path: /metadata/name
      value: c4
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n4@e1-1,n5@e1-2,n6@e1-3

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n6@eth2
