apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/ixia-c/controller
- ../components/ixia-c/engine-1
- ../components/ixia-c/engine-2
- ../components/networks/p1

patches:
- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: p1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: p1@eth2

- target:
    kind: Pod
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Pod
    metadata:
      name: otg-port-3

- target:
    kind: Service
    name: otg-port-3
  patch: |-
    $patch: delete
    kind: Service
    metadata:
      name: otg-port-3
