apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


components:
- ../components/networks/b0
- ../components/networks/p1
- ../components/ixia-c/controller
- ../components/ixia-c/engine-1
- ../components/ixia-c/engine-2


patches:

- target:
    kind: Pod
    name: otg-controller
  patch: |-
    - op: replace
      path: /metadata/annotations/v1.multus-cni.io~1default-network
      value: b0@eth0

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/v1.multus-cni.io~1default-network
      value: b0@eth0
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: p1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/v1.multus-cni.io~1default-network
      value: b0@eth0
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: p1@eth2
