apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


components:
- ../components/networks/b0
- ../components/networks/b1
- ../components/csr/csr01
- ../components/csr/csr02


patches:

- target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: csr01
  patch: |-
    - op: replace
      path: /spec/template/spec/networks/0/multus/networkName
      value: kube-system/b0
    - op: replace
      path: /spec/template/spec/networks/1/multus/networkName
      value: b1

- target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: csr02
  patch: |-
    - op: replace
      path: /spec/template/spec/networks/0/multus/networkName
      value: kube-system/b0
    - op: replace
      path: /spec/template/spec/networks/1/multus/networkName
      value: b1
