apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


components:
- ../components/csr/csr01
- ../components/ixia-c
- ../components/networks/b0
- ../components/networks/b1
- ../components/networks/b2
- ../components/networks/b3


patches:

- target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: csr01
  patch: |-
    - op: replace
      path: /spec/template/spec/networks/0/multus/networkName
      value: kube-system/b0
    - op: replace
      path: /spec/template/spec/networks/1/multus/networkName
      value: b1
    - op: add
      path: /spec/template/spec/networks/2
      value:
        name: ge3
        multus:
          networkName: b2
    - op: add
      path: /spec/template/spec/networks/3
      value:
        name: ge4
        multus:
          networkName: b3
    - op: add
      path: /spec/template/spec/domain/devices/interfaces/2
      value:
        name: ge3
        bridge: {}
    - op: add
      path: /spec/template/spec/domain/devices/interfaces/3
      value:
        name: ge4
        bridge: {}

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b2@eth2

- target:
    kind: Pod
    name: otg-port-3
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: b3@eth3
