apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


components:
- ../components/networks
- ../components/csr
- ../components/ixia-c


patches:

- target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: csr01
  patch: |-
    - op: replace
      path: /spec/template/spec/networks/1/multus/networkName
      value: n1
    - op: add
      path: /spec/template/spec/networks/2
      value:
        name: ge3
        multus:
          networkName: n2
    - op: add
      path: /spec/template/spec/networks/3
      value:
        name: ge4
        multus:
          networkName: n3
    - op: add
      path: /spec/template/spec/domain/devices/interfaces/2
      value:
        name: ge3
        bridge: {}
    - op: add
      path: /spec/template/spec/domain/devices/interfaces/3
      value:
        name: ge4
        bridge: {}


- target:
    group: kubevirt.io
    version: v1
    kind: VirtualMachine
    name: csr02
  patch: |-
    $patch: delete
    kind: VirtualMachine
    metadata:
      name: csr02

- target:
    group: cdi.kubevirt.io
    version: v1beta1
    kind: DataVolume
    name: csr02
  patch: |-
    $patch: delete
    kind: DataVolume
    metadata:
      name: csr02

- target:
    kind: Pod
    name: otg-port-1
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n1@eth1

- target:
    kind: Pod
    name: otg-port-2
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n2@eth2

- target:
    kind: Pod
    name: otg-port-3
  patch: |-
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: n3@eth3
