apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n1",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n2",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n3",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n4",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n5
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n5",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n6
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "n6",
      "plugins": [
        {
          "type": "pod2pod"
        }
      ]
    }'
