apiVersion: v1
kind: Pod
metadata:
  name: otg-controller
  annotations:
    v1.multus-cni.io/default-network: cni1
  labels:
    app: ixia-c
    role: controller
spec:
  containers:
    - name: otg-controller
      image: ghcr.io/open-traffic-generator/keng-controller:latest
      args:
        - --accept-eula
        - --debug
      volumeMounts:
        - mountPath: /home/ixia-c/controller/config
          name: config
          readOnly: true
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
    - name: otg-gnmi-server
      image: ghcr.io/open-traffic-generator/otg-gnmi-server:latest
      args:
        - -http-server
        - https://localhost:8443
        - --debug
      ports:
        - containerPort: 50051
          name: gnmi-port
          protocol: TCP
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
  restartPolicy: Always
  volumes:
    - configMap:
        defaultMode: 420
        name: otg-controller-config
      name: config
