apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: b4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "b4",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "b4",
          "ipam": {}
        },
        {
          "type": "accept-bridge",
          "name": "b4"
        }
      ]
    }'
