apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: csr02
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  source:
    http:
      url: http://${HTTP_SERVER_IP}:8080/csr1000v-universalk9.17.03.04a-serial.qcow2
