apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: csr02day0
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
  source:
    http:
      url: http://172.18.0.1:8080/csr_config.iso
